"""Initial migration

Revision ID: 66ecb76f2038
Revises: 
Create Date: 2025-05-08 00:32:52.399135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ecb76f2038'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bakery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('zip_code', sa.String(length=4), nullable=False),
    sa.Column('street_name', sa.String(length=80), nullable=False),
    sa.Column('street_number', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bakery', schema=None) as batch_op:
        batch_op.create_index('idx_bakery_name', ['name'], unique=False)
        batch_op.create_index('idx_bakery_street', ['street_name', 'street_number'], unique=False)
        batch_op.create_index('idx_bakery_zip', ['zip_code'], unique=False)

    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index('idx_category_name', ['name'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=24), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('profile_picture', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('idx_user_email', ['email'], unique=True)
        batch_op.create_index('idx_user_username', ['username'], unique=True)

    op.create_table('bakery_review',
    sa.Column('bakery_id', sa.Integer(), nullable=False),
    sa.Column('service_rating', sa.Integer(), nullable=True),
    sa.Column('price_rating', sa.Integer(), nullable=True),
    sa.Column('atmosphere_rating', sa.Integer(), nullable=True),
    sa.Column('location_rating', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('overall_rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('atmosphere_rating IS NULL OR atmosphere_rating BETWEEN 1 AND 10', name='check_bakery_atmosphere_rating'),
    sa.CheckConstraint('location_rating IS NULL OR location_rating BETWEEN 1 AND 10', name='check_bakery_location_rating'),
    sa.CheckConstraint('overall_rating BETWEEN 1 AND 10', name='check_bakery_overall_rating'),
    sa.CheckConstraint('price_rating IS NULL OR price_rating BETWEEN 1 AND 10', name='check_bakery_price_rating'),
    sa.CheckConstraint('service_rating IS NULL OR service_rating BETWEEN 1 AND 10', name='check_bakery_service_rating'),
    sa.ForeignKeyConstraint(['bakery_id'], ['bakery.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bakery_review', schema=None) as batch_op:
        batch_op.create_index('idx_bakery_review_bakery_id', ['bakery_id'], unique=False)
        batch_op.create_index('idx_bakery_review_user_id', ['user_id'], unique=False)

    op.create_table('subcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subcategory', schema=None) as batch_op:
        batch_op.create_index('idx_subcategory_category_id', ['category_id'], unique=False)
        batch_op.create_index('idx_subcategory_name', ['name'], unique=False)
        batch_op.create_index('idx_unique_category_subcategory', ['category_id', 'name'], unique=True)

    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('bakery_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bakery_id'], ['bakery.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategory.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index('idx_product_bakery_id', ['bakery_id'], unique=False)
        batch_op.create_index('idx_product_category_id', ['category_id'], unique=False)
        batch_op.create_index('idx_product_name', ['name'], unique=False)
        batch_op.create_index('idx_product_subcategory_id', ['subcategory_id'], unique=False)

    op.create_table('product_review',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('taste_rating', sa.Integer(), nullable=True),
    sa.Column('price_rating', sa.Integer(), nullable=True),
    sa.Column('presentation_rating', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('overall_rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('overall_rating BETWEEN 1 AND 10', name='check_product_overall_rating'),
    sa.CheckConstraint('presentation_rating IS NULL OR presentation_rating BETWEEN 1 AND 10', name='check_product_presentation_rating'),
    sa.CheckConstraint('price_rating IS NULL OR price_rating BETWEEN 1 AND 10', name='check_product_price_rating'),
    sa.CheckConstraint('taste_rating IS NULL OR taste_rating BETWEEN 1 AND 10', name='check_product_taste_rating'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_review', schema=None) as batch_op:
        batch_op.create_index('idx_product_review_product_id', ['product_id'], unique=False)
        batch_op.create_index('idx_product_review_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_review', schema=None) as batch_op:
        batch_op.drop_index('idx_product_review_user_id')
        batch_op.drop_index('idx_product_review_product_id')

    op.drop_table('product_review')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index('idx_product_subcategory_id')
        batch_op.drop_index('idx_product_name')
        batch_op.drop_index('idx_product_category_id')
        batch_op.drop_index('idx_product_bakery_id')

    op.drop_table('product')
    with op.batch_alter_table('subcategory', schema=None) as batch_op:
        batch_op.drop_index('idx_unique_category_subcategory')
        batch_op.drop_index('idx_subcategory_name')
        batch_op.drop_index('idx_subcategory_category_id')

    op.drop_table('subcategory')
    with op.batch_alter_table('bakery_review', schema=None) as batch_op:
        batch_op.drop_index('idx_bakery_review_user_id')
        batch_op.drop_index('idx_bakery_review_bakery_id')

    op.drop_table('bakery_review')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('idx_user_username')
        batch_op.drop_index('idx_user_email')

    op.drop_table('user')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index('idx_category_name')

    op.drop_table('category')
    with op.batch_alter_table('bakery', schema=None) as batch_op:
        batch_op.drop_index('idx_bakery_zip')
        batch_op.drop_index('idx_bakery_street')
        batch_op.drop_index('idx_bakery_name')

    op.drop_table('bakery')
    # ### end Alembic commands ###
