# docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - backend_data:/app/instance
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: >
      bash -c "python init_db.py && 
              python app.py"
    networks:
      - crumbcompass-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:5000
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend
    networks:
      - crumbcompass-network
    restart: unless-stopped

networks:
  crumbcompass-network:
    driver: bridge

volumes:
  backend_data: